name: flutter_admin_tool
description: A package to help you build a flutter admin tool. Setup CRUD operations just by defining the datastructure and implement your backend functionality.
version: 0.0.8
repository: https://github.com/Dix206/flutter_admin_tool

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  equatable: ^2.0.5
  go_router: ^13.2.0
  file_picker: ^6.1.1
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

false_secrets:
 - /example/firebase_example/android/app/google-services.json
 - /example/firebase_example/ios/Runner/GoogleService-Info.plist
 - /example/firebase_example/lib/firebase_options.dart