name: flutter_cms
description: A new Flutter package project.
version: 0.0.1
homepage: "www.example.com" # TODO

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  equatable: ^2.0.5
  go_router: ^5.2.0
  file_picker: ^5.2.5
  intl: ^0.17.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
