name: flat
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/Dix206/flutter_multi_tap_detector

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  equatable: ^2.0.5
  go_router: ^10.1.0
  file_picker: ^5.3.3
  intl: ^0.18.0
  shared_preferences: ^2.2.0
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
