name: flutter_admin_tool
description: A package to help you build a flutter admin tool. Setup CRUD operations just by defining the datastructure and implement your backend functionality.
version: 0.0.7
repository: https://github.com/Dix206/flutter_admin_tool

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  equatable: ^2.0.5
  go_router: ^10.1.0
  file_picker: ^5.3.3
  intl: ^0.18.0
  shared_preferences: ^2.2.0
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:

false_secrets:
 - /example/firebase_example/android/app/google-services.json
 - /example/firebase_example/ios/Runner/GoogleService-Info.plist
 - /example/firebase_example/lib/firebase_options.dart