name: firebase_example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  firebase_storage: ^11.2.6
  cloud_firestore: ^4.8.5
  uuid: ^3.0.7
  go_router: ^10.1.0
  flutter_admin_tool:
      path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
